/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BingoRouteImport } from './routes/bingo'
import { Route as MovieRouteImport } from './routes/movie'
import { Route as MoviePlayRouteImport } from './routes/movie-play'
import { Route as NumberBingoRulesRouteImport } from './routes/number-bingo-rules'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as PlayRouteImport } from './routes/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BingoRoute = BingoRouteImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieRoute = MovieRouteImport.update({
  id: '/movie',
  path: '/movie',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviePlayRoute = MoviePlayRouteImport.update({
  id: '/movie-play',
  path: '/movie-play',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberBingoRulesRoute = NumberBingoRulesRouteImport.update({
  id: '/number-bingo-rules',
  path: '/number-bingo-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bingo': typeof BingoRoute
  '/movie': typeof MovieRoute
  '/movie-play': typeof MoviePlayRoute
  '/number-bingo-rules': typeof NumberBingoRulesRoute
  '/online': typeof OnlineRoute
  '/play': typeof PlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bingo': typeof BingoRoute
  '/movie': typeof MovieRoute
  '/movie-play': typeof MoviePlayRoute
  '/number-bingo-rules': typeof NumberBingoRulesRoute
  '/online': typeof OnlineRoute
  '/play': typeof PlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bingo': typeof BingoRoute
  '/movie': typeof MovieRoute
  '/movie-play': typeof MoviePlayRoute
  '/number-bingo-rules': typeof NumberBingoRulesRoute
  '/online': typeof OnlineRoute
  '/play': typeof PlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bingo'
    | '/movie'
    | '/movie-play'
    | '/number-bingo-rules'
    | '/online'
    | '/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bingo'
    | '/movie'
    | '/movie-play'
    | '/number-bingo-rules'
    | '/online'
    | '/play'
  id:
    | '__root__'
    | '/'
    | '/bingo'
    | '/movie'
    | '/movie-play'
    | '/number-bingo-rules'
    | '/online'
    | '/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BingoRoute: typeof BingoRoute
  MovieRoute: typeof MovieRoute
  MoviePlayRoute: typeof MoviePlayRoute
  NumberBingoRulesRoute: typeof NumberBingoRulesRoute
  OnlineRoute: typeof OnlineRoute
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bingo': {
      id: '/bingo'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie': {
      id: '/movie'
      path: '/movie'
      fullPath: '/movie'
      preLoaderRoute: typeof MovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie-play': {
      id: '/movie-play'
      path: '/movie-play'
      fullPath: '/movie-play'
      preLoaderRoute: typeof MoviePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-bingo-rules': {
      id: '/number-bingo-rules'
      path: '/number-bingo-rules'
      fullPath: '/number-bingo-rules'
      preLoaderRoute: typeof NumberBingoRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BingoRoute: BingoRoute,
  MovieRoute: MovieRoute,
  MoviePlayRoute: MoviePlayRoute,
  NumberBingoRulesRoute: NumberBingoRulesRoute,
  OnlineRoute: OnlineRoute,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
